### ISSUE TITLE
How to generate gestures corresponding to specific semantics？

### ISSUE THREAD

**Issue by liuweie** [ShenhanQian/SpeechDrivesTemplates#17]
Hello, I read your great paper recently ,I don't know much about Co-speech generation task, so I have some questions and would like to ask you for advice:
1. I found that neither your paper nor other similar SOTA papers seem to incorporate too many semantic features, so is this model unable to generate corresponding gestures with specific semantics? For example: When I say "here", can I generate a corresponding pointing gesture?
2. At present, there are two main types of methods for the Co-speech generation task: rule-based method and data-driven method. If I want to generate corresponding gestures in specific semantics, should I combine the effect of the rule-based method?

**Comment by ShenhanQian** [comment]
Thanks for your message. As to you question:
1. Since we only use audio as input, it's hard to measure the correspondence before words and generated gestures. But you can refer to other papers like [HA2G](https://alvinliu0.github.io/projects/HA2G) and [SEEG](https://ffmpbgrnn.github.io/publications/pdf/seeg.pdf), which use text as the input.
2. In my opinion, data-based results are more natural and smooth, and rule-based results are more robust and predictable. It would be interesting if you could combine the advantages of both manners.
